CREATE
OR REPLACE WAREHOUSE DW_TICKETMASTER WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = FALSE;

CREATE DATABASE ticketmaster_analytics;

CREATE SCHEMA bronze;

CREATE SCHEMA silver;

CREATE SCHEMA gold;